version: '3.5'
services:
  dgt-db:
    image: 'postgres:13.1-alpine'
    container_name: dgt-db
    environment:
      - POSTGRES_USER=dgt
      - POSTGRES_PASSWORD=secret
    ports:
      - "127.0.0.1:5432:5432"